"""Central configuration for the Tashkent food-price forecasting project.

Single source of truth for paths, keys, feature-engineering settings, the
time-based split, and model hyper-parameters. Every path is absolute (resolved
from this file's location), so the pipeline runs from any working directory.
"""

from pathlib import Path

# --- paths ------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent            # food_price/
DATA_DIR = ROOT / "datasets"
REPORTS_DIR = ROOT / "reports"
MODELS_DIR = ROOT / "models"
CBU_DIR = DATA_DIR / "cbu"

PRICES_CSV = DATA_DIR / "prices.csv"              # raw target data
WEATHER_CSV = DATA_DIR / "weather_monthly.csv"    # generated by utils/weather.py
POPULATION_CSV = DATA_DIR / "population_monthly.csv"  # generated by utils/population.py
FUEL_CSV = DATA_DIR / "fuel_monthly.csv"          # cache generated by utils/fuel.py
CURRENCY_CSV = DATA_DIR / "currency_monthly.csv"  # cache generated by utils/currency.py

# --- schema -----------------------------------------------------------------
TARGET = "price"
DATE_COL = "date"
GROUP_KEYS = ["product", "district"]              # each pair is its own monthly series

# Uzbek month spellings ACTUALLY present in prices.csv (note sentabr/oktabr, no 'y').
MONTH_MAP = {
    "yanvar": 1, "fevral": 2, "mart": 3, "aprel": 4, "may": 5, "iyun": 6,
    "iyul": 7, "avgust": 8, "sentabr": 9, "sentyabr": 9, "oktabr": 10,
    "oktyabr": 10, "noyabr": 11, "dekabr": 12,
}

# --- feature engineering ----------------------------------------------------
LAGS = (1, 2, 3, 12)          # price lags in months
ROLL_WINDOWS = (3, 6, 12)     # rolling mean/std windows in months
# Numeric columns that are NOT features (identifiers / data-quality flags / trend).
DROP_FEATURES = ["year", "month_num", "n_days"]

# --- train / test split -----------------------------------------------------
# Time-based: every row on/after SPLIT_DATE is the test set (no shuffling, no leakage).
SPLIT_DATE = "2025-09-01"

# --- misc -------------------------------------------------------------------
RANDOM_STATE = 42
